apiVersion: v1
kind: Service
metadata:
  name: obs-tools-web
  namespace: obs-tools
spec:
  selector: { app: obs-tools-web }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
